In [5]:
a= -5
b = 6
c = a+b
print(c)

1

In [6]:
abs(a)

5

In [7]:
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
Apple = yf.download("AAPL", start = "2010-01-01",end ="2021-01-01")

/var/folders/4z/0p4c7jt52_d1bq34q6bc_x800000gn/T/ipykernel_48694/917510246.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  Apple = yf.download("AAPL", start = "2010-01-01",end ="2021-01-01")
[*********************100%***********************]  1 of 1 completed

In [9]:
Apple

Price            Close        High         Low        Open     Volume
Ticker            AAPL        AAPL        AAPL        AAPL       AAPL
Date
2010-01-04    6.431896    6.446622    6.382907    6.414464  493729600
2010-01-05    6.443014    6.479380    6.409053    6.449626  601904800
2010-01-06    6.340532    6.468563    6.333920    6.443017  552160000
2010-01-07    6.328811    6.371488    6.282828    6.363974  477131200
2010-01-08    6.370886    6.371488    6.283129    6.320395  447610800
...                ...         ...         ...         ...        ...
2020-12-24  128.736969  130.190472  127.888287  128.102899   54930100
2020-12-28  133.341354  133.975425  130.239251  130.707502  124486200
2020-12-29  131.565933  135.389899  131.048918  134.668037  121047300
2020-12-30  130.444092  132.658485  130.131924  132.258526   96452100
2020-12-31  129.439362  131.439144  128.493123  130.795309   99116600

[2769 rows x 5 columns]

In [10]:
 a = [1,2,3,5]
a

[1, 2, 3, 5]

In [11]:
ticker=["SPY","AAPL","KO"]

In [12]:
stocks = yf.download(ticker, start = "2010-01-01",end ="2021-01-01")

/var/folders/4z/0p4c7jt52_d1bq34q6bc_x800000gn/T/ipykernel_48694/2560042617.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  stocks = yf.download(ticker, start = "2010-01-01",end ="2021-01-01")
[*********************100%***********************]  3 of 3 completed

In [13]:
stocks

Price            Close                               High             \
Ticker            AAPL         KO         SPY        AAPL         KO
Date
2010-01-04    6.431896  17.692518   85.515640    6.446622  17.748350
2010-01-05    6.443014  17.478497   85.741989    6.479380  17.677011
2010-01-06    6.340532  17.472286   85.802345    6.468563  17.506405
2010-01-07    6.328811  17.428867   86.164551    6.371488  17.484699
2010-01-08    6.370886  17.106279   86.451309    6.371488  17.258266
...                ...        ...         ...         ...        ...
2020-12-24  128.736969  46.655010  346.428406  130.190472  46.751045
2020-12-28  133.341354  47.283604  349.404480  133.975425  47.528053
2020-12-29  131.565933  47.257408  348.737915  135.389899  47.571701
2020-12-30  130.444092  47.528038  349.235504  132.658485  47.693917
2020-12-31  129.439362  47.877266  351.009827  131.439144  47.955839

Price                          Low                               Open  \
Ticker             SPY        AAPL         KO         SPY        AAPL
Date
2010-01-04   85.560913    6.382907  17.649094   84.142320    6.414464
2010-01-05   85.779720    6.409053  17.413360   85.153424    6.449626
2010-01-06   86.013624    6.333920  17.363723   85.591066    6.443017
2010-01-07   86.270190    6.282828  17.292390   85.402432    6.363974
2010-01-08   86.489040    6.283129  16.982208   85.764652    6.320395
...                ...         ...        ...         ...         ...
2020-12-24  346.456570  127.888287  46.288337  344.973230  128.102899
2020-12-28  349.798773  130.239251  46.908198  348.371761  130.707502
2020-12-29  351.122552  131.048918  47.161374  348.146447  134.668037
2020-12-30  350.277621  130.131924  47.170094  348.841211  132.258526
2020-12-31  351.742113  128.493123  47.379636  348.521932  130.795309

Price                                 Volume
Ticker             KO         SPY       AAPL        KO        SPY
Date
2010-01-04  17.729739   84.791252  493729600  13870400  118944600
2010-01-05  17.633585   85.462801  601904800  23172400  111579900
2010-01-06  17.478489   85.658975  552160000  19264600  116074400
2010-01-07  17.472293   85.643894  477131200  13234600  131091100
2010-01-08  17.202434   85.938200  447610800  28712400  126402800
...               ...         ...        ...       ...        ...
2020-12-24  46.288337  345.564669   54930100   3265500   26457900
2020-12-28  47.012961  349.000761  124486200   9020500   39000400
2020-12-29  47.536779  350.944172  121047300   8320600   53680500
2020-12-30  47.187555  349.564101   96452100   8142700   49455300
2020-12-31  47.536783  349.038278   99116600   8495000   78520700

[2769 rows x 15 columns]

In [14]:
stocks.head()

Price          Close                            High                        \
Ticker          AAPL         KO        SPY      AAPL         KO        SPY
Date
2010-01-04  6.431896  17.692518  85.515640  6.446622  17.748350  85.560913
2010-01-05  6.443014  17.478497  85.741989  6.479380  17.677011  85.779720
2010-01-06  6.340532  17.472286  85.802345  6.468563  17.506405  86.013624
2010-01-07  6.328811  17.428867  86.164551  6.371488  17.484699  86.270190
2010-01-08  6.370886  17.106279  86.451309  6.371488  17.258266  86.489040

Price            Low                            Open                        \
Ticker          AAPL         KO        SPY      AAPL         KO        SPY
Date
2010-01-04  6.382907  17.649094  84.142320  6.414464  17.729739  84.791252
2010-01-05  6.409053  17.413360  85.153424  6.449626  17.633585  85.462801
2010-01-06  6.333920  17.363723  85.591066  6.443017  17.478489  85.658975
2010-01-07  6.282828  17.292390  85.402432  6.363974  17.472293  85.643894
2010-01-08  6.283129  16.982208  85.764652  6.320395  17.202434  85.938200

Price          Volume
Ticker           AAPL        KO        SPY
Date
2010-01-04  493729600  13870400  118944600
2010-01-05  601904800  23172400  111579900
2010-01-06  552160000  19264600  116074400
2010-01-07  477131200  13234600  131091100
2010-01-08  447610800  28712400  126402800

In [15]:
stocks.tail()

Price            Close                               High             \
Ticker            AAPL         KO         SPY        AAPL         KO
Date
2020-12-24  128.736969  46.655010  346.428406  130.190472  46.751045
2020-12-28  133.341354  47.283604  349.404480  133.975425  47.528053
2020-12-29  131.565933  47.257408  348.737915  135.389899  47.571701
2020-12-30  130.444092  47.528038  349.235504  132.658485  47.693917
2020-12-31  129.439362  47.877266  351.009827  131.439144  47.955839

Price                          Low                               Open  \
Ticker             SPY        AAPL         KO         SPY        AAPL
Date
2020-12-24  346.456570  127.888287  46.288337  344.973230  128.102899
2020-12-28  349.798773  130.239251  46.908198  348.371761  130.707502
2020-12-29  351.122552  131.048918  47.161374  348.146447  134.668037
2020-12-30  350.277621  130.131924  47.170094  348.841211  132.258526
2020-12-31  351.742113  128.493123  47.379636  348.521932  130.795309

Price                                 Volume
Ticker             KO         SPY       AAPL       KO       SPY
Date
2020-12-24  46.288337  345.564669   54930100  3265500  26457900
2020-12-28  47.012961  349.000761  124486200  9020500  39000400
2020-12-29  47.536779  350.944172  121047300  8320600  53680500
2020-12-30  47.187555  349.564101   96452100  8142700  49455300
2020-12-31  47.536783  349.038278   99116600  8495000  78520700

In [16]:
stocks.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2769 entries, 2010-01-04 to 2020-12-31
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, AAPL)   2769 non-null   float64
 1   (Close, KO)     2769 non-null   float64
 2   (Close, SPY)    2769 non-null   float64
 3   (High, AAPL)    2769 non-null   float64
 4   (High, KO)      2769 non-null   float64
 5   (High, SPY)     2769 non-null   float64
 6   (Low, AAPL)     2769 non-null   float64
 7   (Low, KO)       2769 non-null   float64
 8   (Low, SPY)      2769 non-null   float64
 9   (Open, AAPL)    2769 non-null   float64
 10  (Open, KO)      2769 non-null   float64
 11  (Open, SPY)     2769 non-null   float64
 12  (Volume, AAPL)  2769 non-null   int64
 13  (Volume, KO)    2769 non-null   int64
 14  (Volume, SPY)   2769 non-null   int64
dtypes: float64(12), int64(3)
memory usage: 346.1 KB

In [17]:
stocks.to_csv("stocksYT.csv")

In [18]:
stocks = pd.read_csv("stocksYT.csv")

In [19]:
stocks

,Price,Close,Close.1,Close.2,High,High.1,High.2,Low,Low.1,Low.2,Open,Open.1,Open.2,Volume,Volume.1,Volume.2
0,Ticker,AAPL,KO,SPY,AAPL,KO,SPY,AAPL,KO,SPY,AAPL,KO,SPY,AAPL,KO,SPY
1,Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010-01-04,6.431896686553955,17.6925106048584,85.7684326171875,6.44662317438684,17.748342604456653,85.81383892159324,6.382908442941151,17.64908597922249,84.39105223541063,6.414465259906861,17.729731543513132,85.0419028769701,493729600,13870400,118944600
3,2010-01-05,6.443014621734619,17.47849464416504,85.99546813964844,6.47938020544434,17.677009158491817,86.03331057516952,6.409053025931428,17.41335767925597,85.40516309876742,6.449626691960587,17.63358333198632,85.71545490299437,601904800,23172400,111579900
4,2010-01-06,6.340531826019287,17.472291946411133,86.05601501464844,6.46856277868648,17.506410463442354,86.26791879926948,6.333919753827397,17.36372915618635,85.8441112300274,6.443016537393572,17.478494452611155,85.91222068625055,552160000,19264600,116074400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2766,2020-12-24,128.7369384765625,46.655006408691406,347.4524841308594,130.19044111904873,46.75104082696976,347.48073115088,127.88825690620341,46.28833317202727,345.99300687058974,128.10286843422077,46.28833317202727,346.58619429102185,54930100,3265500,26457900
2767,2020-12-28,133.34136962890625,47.283592224121094,350.43743896484375,133.97543996952834,47.528041045037355,350.83289730413503,130.23926555506839,46.908186774648016,349.40166685034325,130.7075172282758,47.01295007927422,350.0325266367698,124486200,9020500,39000400
2768,2020-12-29,131.56593322753906,47.25740432739258,349.7688903808594,135.38989879452387,47.571697585581944,352.160577213229,131.04891842415702,47.16136990623854,349.1756741156765,134.66803693280866,47.53677537236856,351.98166980831576,121047300,8320600,53680500
2769,2020-12-30,130.44410705566406,47.52804183959961,350.2679138183594,132.65850039720306,47.69392068259341,351.31311114354594,130.1319393225058,47.170097489974445,349.8724554951741,132.25854107096032,47.18755859609829,350.59748157803176,96452100,8142700,49455300
2770,2020-12-31,129.43934631347656,47.877254486083984,352.0475769042969,131.4391281363561,47.95582779383832,352.78202827011904,128.4931083029186,47.37962464709498,349.5523273111529,130.79529332577445,47.53677126260364,350.070199000767,99116600,8495000,78520700

In [20]:
stocks = pd.read_csv("stocksYT.csv",header=[0,1])
stocks

           Price       Close                               High             \
          Ticker        AAPL         KO         SPY        AAPL         KO
0           Date         NaN        NaN         NaN         NaN        NaN
1     2010-01-04    6.431897  17.692511   85.768433    6.446623  17.748343
2     2010-01-05    6.443015  17.478495   85.995468    6.479380  17.677009
3     2010-01-06    6.340532  17.472292   86.056015    6.468563  17.506410
4     2010-01-07    6.328810  17.428865   86.419296    6.371488  17.484697
...          ...         ...        ...         ...         ...        ...
2765  2020-12-24  128.736938  46.655006  347.452484  130.190441  46.751041
2766  2020-12-28  133.341370  47.283592  350.437439  133.975440  47.528041
2767  2020-12-29  131.565933  47.257404  349.768890  135.389899  47.571698
2768  2020-12-30  130.444107  47.528042  350.267914  132.658500  47.693921
2769  2020-12-31  129.439346  47.877254  352.047577  131.439128  47.955828

                         Low                               Open             \
             SPY        AAPL         KO         SPY        AAPL         KO
0            NaN         NaN        NaN         NaN         NaN        NaN
1      85.813839    6.382908  17.649086   84.391052    6.414465  17.729732
2      86.033311    6.409053  17.413358   85.405163    6.449627  17.633583
3      86.267919    6.333920  17.363729   85.844111    6.443017  17.478494
4      86.525248    6.282827  17.292388   85.654924    6.363974  17.472291
...          ...         ...        ...         ...         ...        ...
2765  347.480731  127.888257  46.288333  345.993007  128.102868  46.288333
2766  350.832897  130.239266  46.908187  349.401667  130.707517  47.012950
2767  352.160577  131.048918  47.161370  349.175674  134.668037  47.536775
2768  351.313111  130.131939  47.170097  349.872455  132.258541  47.187559
2769  352.782028  128.493108  47.379625  349.552327  130.795293  47.536771

                       Volume
             SPY         AAPL          KO          SPY
0            NaN          NaN         NaN          NaN
1      85.041903  493729600.0  13870400.0  118944600.0
2      85.715455  601904800.0  23172400.0  111579900.0
3      85.912221  552160000.0  19264600.0  116074400.0
4      85.897101  477131200.0  13234600.0  131091100.0
...          ...          ...         ...          ...
2765  346.586194   54930100.0   3265500.0   26457900.0
2766  350.032527  124486200.0   9020500.0   39000400.0
2767  351.981670  121047300.0   8320600.0   53680500.0
2768  350.597482   96452100.0   8142700.0   49455300.0
2769  350.070199   99116600.0   8495000.0   78520700.0

[2770 rows x 16 columns]

In [21]:
stocks = pd.read_csv("stocksYT.csv",header=[0,1],index_col=[0])
stocks

Price            Close                               High             \
Ticker            AAPL         KO         SPY        AAPL         KO
Date
2010-01-04    6.431897  17.692511   85.768433    6.446623  17.748343
2010-01-05    6.443015  17.478495   85.995468    6.479380  17.677009
2010-01-06    6.340532  17.472292   86.056015    6.468563  17.506410
2010-01-07    6.328810  17.428865   86.419296    6.371488  17.484697
2010-01-08    6.370887  17.106283   86.706886    6.371488  17.258269
...                ...        ...         ...         ...        ...
2020-12-24  128.736938  46.655006  347.452484  130.190441  46.751041
2020-12-28  133.341370  47.283592  350.437439  133.975440  47.528041
2020-12-29  131.565933  47.257404  349.768890  135.389899  47.571698
2020-12-30  130.444107  47.528042  350.267914  132.658500  47.693921
2020-12-31  129.439346  47.877254  352.047577  131.439128  47.955828

Price                          Low                               Open  \
Ticker             SPY        AAPL         KO         SPY        AAPL
Date
2010-01-04   85.813839    6.382908  17.649086   84.391052    6.414465
2010-01-05   86.033311    6.409053  17.413358   85.405163    6.449627
2010-01-06   86.267919    6.333920  17.363729   85.844111    6.443017
2010-01-07   86.525248    6.282827  17.292388   85.654924    6.363974
2010-01-08   86.744729    6.283129  16.982212   86.018199    6.320396
...                ...         ...        ...         ...         ...
2020-12-24  347.480731  127.888257  46.288333  345.993007  128.102868
2020-12-28  350.832897  130.239266  46.908187  349.401667  130.707517
2020-12-29  352.160577  131.048918  47.161370  349.175674  134.668037
2020-12-30  351.313111  130.131939  47.170097  349.872455  132.258541
2020-12-31  352.782028  128.493108  47.379625  349.552327  130.795293

Price                                 Volume
Ticker             KO         SPY       AAPL        KO        SPY
Date
2010-01-04  17.729732   85.041903  493729600  13870400  118944600
2010-01-05  17.633583   85.715455  601904800  23172400  111579900
2010-01-06  17.478494   85.912221  552160000  19264600  116074400
2010-01-07  17.472291   85.897101  477131200  13234600  131091100
2010-01-08  17.202437   86.192260  447610800  28712400  126402800
...               ...         ...        ...       ...        ...
2020-12-24  46.288333  346.586194   54930100   3265500   26457900
2020-12-28  47.012950  350.032527  124486200   9020500   39000400
2020-12-29  47.536775  351.981670  121047300   8320600   53680500
2020-12-30  47.187559  350.597482   96452100   8142700   49455300
2020-12-31  47.536771  350.070199   99116600   8495000   78520700

[2769 rows x 15 columns]

In [22]:
stocks = pd.read_csv("stocksYT.csv",header=[0,1],index_col=[0], parse_dates=[0])
stocks

Price            Close                               High             \
Ticker            AAPL         KO         SPY        AAPL         KO
Date
2010-01-04    6.431897  17.692511   85.768433    6.446623  17.748343
2010-01-05    6.443015  17.478495   85.995468    6.479380  17.677009
2010-01-06    6.340532  17.472292   86.056015    6.468563  17.506410
2010-01-07    6.328810  17.428865   86.419296    6.371488  17.484697
2010-01-08    6.370887  17.106283   86.706886    6.371488  17.258269
...                ...        ...         ...         ...        ...
2020-12-24  128.736938  46.655006  347.452484  130.190441  46.751041
2020-12-28  133.341370  47.283592  350.437439  133.975440  47.528041
2020-12-29  131.565933  47.257404  349.768890  135.389899  47.571698
2020-12-30  130.444107  47.528042  350.267914  132.658500  47.693921
2020-12-31  129.439346  47.877254  352.047577  131.439128  47.955828

Price                          Low                               Open  \
Ticker             SPY        AAPL         KO         SPY        AAPL
Date
2010-01-04   85.813839    6.382908  17.649086   84.391052    6.414465
2010-01-05   86.033311    6.409053  17.413358   85.405163    6.449627
2010-01-06   86.267919    6.333920  17.363729   85.844111    6.443017
2010-01-07   86.525248    6.282827  17.292388   85.654924    6.363974
2010-01-08   86.744729    6.283129  16.982212   86.018199    6.320396
...                ...         ...        ...         ...         ...
2020-12-24  347.480731  127.888257  46.288333  345.993007  128.102868
2020-12-28  350.832897  130.239266  46.908187  349.401667  130.707517
2020-12-29  352.160577  131.048918  47.161370  349.175674  134.668037
2020-12-30  351.313111  130.131939  47.170097  349.872455  132.258541
2020-12-31  352.782028  128.493108  47.379625  349.552327  130.795293

Price                                 Volume
Ticker             KO         SPY       AAPL        KO        SPY
Date
2010-01-04  17.729732   85.041903  493729600  13870400  118944600
2010-01-05  17.633583   85.715455  601904800  23172400  111579900
2010-01-06  17.478494   85.912221  552160000  19264600  116074400
2010-01-07  17.472291   85.897101  477131200  13234600  131091100
2010-01-08  17.202437   86.192260  447610800  28712400  126402800
...               ...         ...        ...       ...        ...
2020-12-24  46.288333  346.586194   54930100   3265500   26457900
2020-12-28  47.012950  350.032527  124486200   9020500   39000400
2020-12-29  47.536775  351.981670  121047300   8320600   53680500
2020-12-30  47.187559  350.597482   96452100   8142700   49455300
2020-12-31  47.536771  350.070199   99116600   8495000   78520700

[2769 rows x 15 columns]

In [23]:
stocks.columns

MultiIndex([( 'Close', 'AAPL'),
            ( 'Close',   'KO'),
            ( 'Close',  'SPY'),
            (  'High', 'AAPL'),
            (  'High',   'KO'),
            (  'High',  'SPY'),
            (   'Low', 'AAPL'),
            (   'Low',   'KO'),
            (   'Low',  'SPY'),
            (  'Open', 'AAPL'),
            (  'Open',   'KO'),
            (  'Open',  'SPY'),
            ('Volume', 'AAPL'),
            ('Volume',   'KO'),
            ('Volume',  'SPY')],
           names=['Price', 'Ticker'])

In [24]:
#convert mult index to one tuple
stocks.columns=stocks.columns.to_flat_index()

In [25]:
stocks.columns

Index([ ('Close', 'AAPL'),    ('Close', 'KO'),   ('Close', 'SPY'),
         ('High', 'AAPL'),     ('High', 'KO'),    ('High', 'SPY'),
          ('Low', 'AAPL'),      ('Low', 'KO'),     ('Low', 'SPY'),
         ('Open', 'AAPL'),     ('Open', 'KO'),    ('Open', 'SPY'),
       ('Volume', 'AAPL'),   ('Volume', 'KO'),  ('Volume', 'SPY')],
      dtype='object')

In [26]:
stocks

,"(Close, AAPL)","(Close, KO)","(Close, SPY)","(High, AAPL)","(High, KO)","(High, SPY)","(Low, AAPL)","(Low, KO)","(Low, SPY)","(Open, AAPL)","(Open, KO)","(Open, SPY)","(Volume, AAPL)","(Volume, KO)","(Volume, SPY)"
Date,,,,,,,,,,,,,,,
2010-01-04,6.431897,17.692511,85.768433,6.446623,17.748343,85.813839,6.382908,17.649086,84.391052,6.414465,17.729732,85.041903,493729600,13870400,118944600
2010-01-05,6.443015,17.478495,85.995468,6.479380,17.677009,86.033311,6.409053,17.413358,85.405163,6.449627,17.633583,85.715455,601904800,23172400,111579900
2010-01-06,6.340532,17.472292,86.056015,6.468563,17.506410,86.267919,6.333920,17.363729,85.844111,6.443017,17.478494,85.912221,552160000,19264600,116074400
2010-01-07,6.328810,17.428865,86.419296,6.371488,17.484697,86.525248,6.282827,17.292388,85.654924,6.363974,17.472291,85.897101,477131200,13234600,131091100
2010-01-08,6.370887,17.106283,86.706886,6.371488,17.258269,86.744729,6.283129,16.982212,86.018199,6.320396,17.202437,86.192260,447610800,28712400,126402800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-24,128.736938,46.655006,347.452484,130.190441,46.751041,347.480731,127.888257,46.288333,345.993007,128.102868,46.288333,346.586194,54930100,3265500,26457900
2020-12-28,133.341370,47.283592,350.437439,133.975440,47.528041,350.832897,130.239266,46.908187,349.401667,130.707517,47.012950,350.032527,124486200,9020500,39000400
2020-12-29,131.565933,47.257404,349.768890,135.389899,47.571698,352.160577,131.048918,47.161370,349.175674,134.668037,47.536775,351.981670,121047300,8320600,53680500
2020-12-30,130.444107,47.528042,350.267914,132.658500,47.693921,351.313111,130.131939,47.170097,349.872455,132.258541,47.187559,350.597482,96452100,8142700,49455300
2020-12-31,129.439346,47.877254,352.047577,131.439128,47.955828,352.782028,128.493108,47.379625,349.552327,130.795293,47.536771,350.070199,99116600,8495000,78520700

In [27]:
stocks.columns=pd.MultiIndex.from_tuples(stocks.columns)
stocks

                 Close                               High             \
                  AAPL         KO         SPY        AAPL         KO
Date
2010-01-04    6.431897  17.692511   85.768433    6.446623  17.748343
2010-01-05    6.443015  17.478495   85.995468    6.479380  17.677009
2010-01-06    6.340532  17.472292   86.056015    6.468563  17.506410
2010-01-07    6.328810  17.428865   86.419296    6.371488  17.484697
2010-01-08    6.370887  17.106283   86.706886    6.371488  17.258269
...                ...        ...         ...         ...        ...
2020-12-24  128.736938  46.655006  347.452484  130.190441  46.751041
2020-12-28  133.341370  47.283592  350.437439  133.975440  47.528041
2020-12-29  131.565933  47.257404  349.768890  135.389899  47.571698
2020-12-30  130.444107  47.528042  350.267914  132.658500  47.693921
2020-12-31  129.439346  47.877254  352.047577  131.439128  47.955828

                               Low                               Open  \
                   SPY        AAPL         KO         SPY        AAPL
Date
2010-01-04   85.813839    6.382908  17.649086   84.391052    6.414465
2010-01-05   86.033311    6.409053  17.413358   85.405163    6.449627
2010-01-06   86.267919    6.333920  17.363729   85.844111    6.443017
2010-01-07   86.525248    6.282827  17.292388   85.654924    6.363974
2010-01-08   86.744729    6.283129  16.982212   86.018199    6.320396
...                ...         ...        ...         ...         ...
2020-12-24  347.480731  127.888257  46.288333  345.993007  128.102868
2020-12-28  350.832897  130.239266  46.908187  349.401667  130.707517
2020-12-29  352.160577  131.048918  47.161370  349.175674  134.668037
2020-12-30  351.313111  130.131939  47.170097  349.872455  132.258541
2020-12-31  352.782028  128.493108  47.379625  349.552327  130.795293

                                      Volume
                   KO         SPY       AAPL        KO        SPY
Date
2010-01-04  17.729732   85.041903  493729600  13870400  118944600
2010-01-05  17.633583   85.715455  601904800  23172400  111579900
2010-01-06  17.478494   85.912221  552160000  19264600  116074400
2010-01-07  17.472291   85.897101  477131200  13234600  131091100
2010-01-08  17.202437   86.192260  447610800  28712400  126402800
...               ...         ...        ...       ...        ...
2020-12-24  46.288333  346.586194   54930100   3265500   26457900
2020-12-28  47.012950  350.032527  124486200   9020500   39000400
2020-12-29  47.536775  351.981670  121047300   8320600   53680500
2020-12-30  47.187559  350.597482   96452100   8142700   49455300
2020-12-31  47.536771  350.070199   99116600   8495000   78520700

[2769 rows x 15 columns]

In [28]:
stocks.columns

MultiIndex([( 'Close', 'AAPL'),
            ( 'Close',   'KO'),
            ( 'Close',  'SPY'),
            (  'High', 'AAPL'),
            (  'High',   'KO'),
            (  'High',  'SPY'),
            (   'Low', 'AAPL'),
            (   'Low',   'KO'),
            (   'Low',  'SPY'),
            (  'Open', 'AAPL'),
            (  'Open',   'KO'),
            (  'Open',  'SPY'),
            ('Volume', 'AAPL'),
            ('Volume',   'KO'),
            ('Volume',  'SPY')],
           )

In [29]:
stocks.describe()

             Close                                   High               \
              AAPL           KO          SPY         AAPL           KO
count  2769.000000  2769.000000  2769.000000  2769.000000  2769.000000
mean     31.333110    30.806220   179.207609    31.646741    31.005063
std      24.435847     7.827362    68.614384    24.755014     7.896652
min       5.771906    15.660819    78.033234     5.890620    15.862685
25%      15.090804    25.447002   113.086075    15.215707    25.579164
50%      24.370777    30.385519   173.231140    24.688734    30.527936
75%      40.634071    35.989967   238.152313    40.964248    36.166395
max     133.341370    50.758629   352.047577   135.389899    50.758629

                            Low                                   Open  \
               SPY         AAPL           KO          SPY         AAPL
count  2769.000000  2769.000000  2769.000000  2769.000000  2769.000000
mean    180.108980    30.993604    30.597663   178.169038    31.320010
std      68.992360    24.087514     7.761838    68.220467    24.424885
min      78.964747     5.717808    15.600936    77.216243     5.781523
25%     113.581874    14.933624    25.270056   112.509501    15.049144
50%     174.147512    24.148620    30.148808   172.390518    24.437425
75%     239.419208    40.365818    35.793863   236.407455    40.615213
max     356.360116   131.048918    50.328108   349.872455   134.668037

                                       Volume
                KO          SPY          AAPL            KO           SPY
count  2769.000000  2769.000000  2.769000e+03  2.769000e+03  2.769000e+03
mean     30.802680   179.183881  2.866162e+08  1.502133e+07  1.244573e+08
std       7.829583    68.628524  2.289459e+08  6.716946e+06  7.477756e+07
min      15.751503    78.728053  4.544800e+07  2.996300e+06  2.027000e+07
25%      25.413615   113.046120  1.211120e+08  1.071810e+07  7.292670e+07
50%      30.278690   173.147405  2.029972e+08  1.350830e+07  1.045961e+08
75%      35.989960   238.357029  3.890376e+08  1.751480e+07  1.539926e+08
max      50.488496   351.981670  1.880998e+09  9.896750e+07  7.178287e+08

In [30]:
close=stocks.loc[:,"Close"].copy()

In [31]:
close

                  AAPL         KO         SPY
Date
2010-01-04    6.431897  17.692511   85.768433
2010-01-05    6.443015  17.478495   85.995468
2010-01-06    6.340532  17.472292   86.056015
2010-01-07    6.328810  17.428865   86.419296
2010-01-08    6.370887  17.106283   86.706886
...                ...        ...         ...
2020-12-24  128.736938  46.655006  347.452484
2020-12-28  133.341370  47.283592  350.437439
2020-12-29  131.565933  47.257404  349.768890
2020-12-30  130.444107  47.528042  350.267914
2020-12-31  129.439346  47.877254  352.047577

[2769 rows x 3 columns]

In [32]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use("seaborn")

OSError: 'seaborn' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)

In [ ]:
close.plot(figsize=(15,8),fontsize=12)
plt.legend(fontsize=12)
plt.show()

In [ ]:
close.iloc[0,0]

In [ ]:
close.AAPL

In [ ]:
close.AAPL.div(close.iloc[0,0])

In [ ]:
close.AAPL.div(close.iloc[0,0]).mul(100)

In [ ]:
close.iloc[0]

In [ ]:
close.div(close.iloc[0]).mul(100)

In [ ]:
normclose=close.div(close.iloc[0]).mul(100)

In [ ]:
normclose.plot(figsize=(15,8),fontsize=12)
plt.legend(fontsize=12)
plt.show()

In [ ]:
aapl= close.AAPL.copy().to_frame()

In [ ]:
aapl

In [ ]:
aapl.shift(periods=1)

In [ ]:
aapl["lag1"]=aapl.shift(periods=1)

In [ ]:
aapl

In [ ]:
aapl["Diff"]=aapl.AAPL.sub(aapl.lag1)

In [ ]:
aapl

In [ ]:
aapl["% Change"]=aapl.AAPL.div(aapl.lag1).sub(1).mul(100)

In [ ]:
aapl

In [ ]:
aapl["Diff2"]=aapl.AAPL.diff(periods=1)
aapl

In [ ]:
aapl["% Change 2"]=aapl.AAPL.pct_change(periods=1).mul(100)

In [ ]:
aapl

In [ ]:
del aapl["% Change"]

In [ ]:
aapl

In [ ]:
aapl.rename(columns = {'% Change 2':'Change'}, inplace = True)

In [ ]:
aapl

In [ ]:
aapl.AAPL.resample("M").last()

In [ ]:
aapl.AAPL.resample("BM").last().pct_change(periods=1).mul(100)

In [ ]:
aapl

In [ ]:
del aapl["Change"]
del aapl["Diff2"]
del aapl["Diff"]
del aapl["lag1"]

In [ ]:
aapl

In [ ]:
ret = aapl.pct_change().dropna()

In [ ]:
ret.info()

In [ ]:
ret.plot(kind="hist",figsize=(12,8), bins=100)
plt.show()

In [ ]:
daily_mean_ret=ret.mean()
daily_mean_ret

In [ ]:
var_daily=ret.var()
var_daily

In [ ]:
std_daily=np.sqrt(var_daily)

In [ ]:
std_daily

In [ ]:
ret.std()

In [ ]:
annual_mean_ret=daily_mean_ret*252
annual_mean_ret

In [ ]:
annual_var_return=var_daily*252
annual_var_return

In [ ]:
annual_std_retuens=np.sqrt(annual_var_return)

In [ ]:
annual_std_retuens

In [ ]:
ret.std()*np.sqrt(252)

In [ ]:
ticker=["SPY","AAPL","KO","IBM","DIS","MSFT"]

In [ ]:
stocks = yf.download(ticker, start = "2010-01-01",end ="2021-01-01")

In [ ]:
close=stocks.loc[:,"Close"].copy()

In [ ]:
normclose=close.div(close.iloc[0]).mul(100)

In [ ]:
normclose.plot(figsize=(15,8),fontsize=12)
plt.legend(fontsize=12)
plt.show()

In [ ]:
ret=close.pct_change().dropna()
ret.head()

In [ ]:
ret.describe().T

In [ ]:
summary=ret.describe().T.loc[:,["mean","std"]]
summary

In [ ]:
summary["mean"]=summary["mean"]*252
summary["std"]=summary["std"]*np.sqrt(252)
summary

In [ ]:
summary.plot.scatter(x="std",y="mean",figsize=(12,8),s=50,fontsize=15)
for i in summary.index:
    plt.annotate(i,xy=(summary.loc[i,"std"]+0.002,summary.loc[i,"mean"]+0.002),size=15)
plt.xlabel("Annual risk(std)",fontsize = 15)
plt.ylabel("Annual return",fontsize = 15)
plt.title("Risk/return",fontsize=25)
plt.show()

In [ ]:
fruits = ["aaple","banaba","mango"]
for i in fruits:
    print(i)

In [ ]:
fruits[1]

## Correlation and Covariance

In [ ]:
# comment

In [ ]:
ret

In [ ]:
ret.cov()

In [ ]:
ret.corr()

In [ ]:
import seaborn as sns

In [ ]:
plt.figure(figsize=(12,8))
sns.set(font_scale=1.4)
sns.heatmap(ret.corr(),cmap="Reds",annot=True,annot_kws={"size":15},vmax=0.6)
plt.show()

## Challenge 1
### Download 20 random stocks and 
### 1. Calcualte risk and reward potential 
### 2. Compare the covariance and coorelation
### 3. Find the best 5 to invest in long term

# Simple returns and log returns

In [ ]:
df = pd.DataFrame(index=[2016,2017,2018],data=[100,50,95],columns=["Price"])

In [ ]:
df

In [ ]:
simplereturns=df.pct_change().dropna()
simplereturns

In [ ]:
simplereturns.mean()

In [ ]:
100*1.2*1.2

In [ ]:
#Mean returns are misleading as crazy

In [ ]:
logreturns=np.log(df/df.shift(1)).dropna()
logreturns

In [ ]:
logreturns.mean()

In [ ]:
100*np.exp(logreturns.mean()*2)

In [ ]:
SPY = yf.download("SPY")

In [ ]:
spy=SPY.Close.to_frame()

In [ ]:
spy

In [ ]:
spy.plot(figsize=(12,8),fontsize=15)
plt.legend(loc="upper left", fontsize=15)
plt.show()

In [ ]:
spy_roll=spy.rolling(window=10)

In [ ]:
spy_roll=spy_roll.mean()

In [ ]:
spy_roll.head(15)

In [ ]:
spy.rolling(window=10).median()

In [ ]:
spy.rolling(window=10).max()

In [ ]:
spy.rolling(window=10,min_periods=5).max()

In [ ]:
spy

In [ ]:
spy["SMA50"]=spy.rolling(window=50,min_periods=50).mean()

In [ ]:
spy

In [ ]:
spy.plot(figsize=(12,8),fontsize=15)
plt.legend(loc="upper left", fontsize=15)
plt.show()

In [ ]:
spy["SMA200"]=spy.Close.rolling(window=200,min_periods=200).mean()
spy

In [ ]:
spy.plot(figsize=(12,8),fontsize=15)
plt.legend(loc="upper left", fontsize=15)
plt.show()

## Challenge 2
### Take the 5 stocks that you picked and plot the moving averages and graph it

In [ ]:
spy["EMA100"]=spy.Close.ewm(span=100,min_periods=100).mean()

In [ ]:
spy

In [ ]:
spy.plot(figsize=(12,8),fontsize=15)
plt.legend(loc="upper left", fontsize=15)
plt.show()

In [ ]:
spy["Day"]=spy.index.day_name()

In [ ]:
spy["Quarter"]=spy.index.quarter

In [ ]:
SPY = yf.download("SPY")

In [ ]:
spy=SPY.Close.to_frame()

In [ ]:
all_days=pd.date_range(start="2010-12-31",end="2020-01-01",freq="D")
all_days

In [ ]:
spy

In [ ]:
spy=spy.reindex(all_days)

In [ ]:
spy

In [ ]:
spy.fillna(method="ffill")

In [ ]:
spy.fillna(method="bfill")

In [ ]:
SPY = yf.download("SPY",interval="1wk")

In [ ]:
SPY

## Cummaltive Returns, Drawdowns etc..

In [ ]:
apple=yf.download("AAPL")

In [ ]:
apple=apple.Close.to_frame()

In [ ]:
apple

In [ ]:
apple["d_returns"]=np.log(apple.div(apple.shift(1)))

In [ ]:
apple

In [ ]:
apple.dropna(inplace=True)

In [ ]:
apple

In [ ]:
apple.d_returns.sum()

In [ ]:
np.exp(apple.d_returns.sum())

In [ ]:
apple["cummreturns"]=apple.d_returns.cumsum().apply(np.exp)

In [ ]:
apple

In [ ]:
apple.cummreturns.plot(figsize=(12,8),title="APPLe buy and hold", fontsize=12)
plt.show()

In [ ]:
apple.d_returns.mean()*252

In [ ]:
apple.d_returns.std()*np.sqrt(252)

In [ ]:
# how to calculate drawdowns
apple["cummmax"]=apple.cummreturns.cummax()

In [ ]:
apple

In [ ]:
apple[["cummreturns","cummmax"]].plot(figsize=(12,8),title="APPLe buy and hold+cummmax", fontsize=12)
plt.show()

In [ ]:
apple["drawdown"]=apple["cummmax"]-apple["cummreturns"]

In [ ]:
apple

In [ ]:
apple.drawdown.max()

In [ ]:
apple.drawdown.idxmax()

In [ ]:
apple.loc[(apple.index<='2020-09-18')]

In [ ]:
apple["drawdown%"]=(apple["cummmax"]-apple["cummreturns"])/apple["cummmax"]

In [ ]:
apple

In [ ]:
apple["drawdown%"].max()

In [ ]:
apple["drawdown%"].idxmax()

In [ ]:
apple.loc[(apple.index<='1997-12-23')]

## SMA Strategy

In [ ]:
data=apple.Close.loc[(apple.index>='1991-01-01')]

In [ ]:
data=data.to_frame()

In [ ]:
data

In [ ]:
sma_s=50
sma_l=100

In [ ]:
data["sma_s"]=data.Close.rolling(sma_s).mean()
data["sma_l"]=data.Close.rolling(sma_l).mean()

In [ ]:
data

In [ ]:
data.plot(figsize=(12,8),title="AAPLE - SMA{} | SMA{}".format(sma_s,sma_l), fontsize=12)

In [ ]:
data.loc["2016"].plot(figsize=(12,8),title="AAPLE - SMA{} | SMA{}".format(sma_s,sma_l), fontsize=12)

In [ ]:
data.dropna(inplace=True)

In [ ]:
data

In [ ]:
data["position"]=np.where(data["sma_s"]>data["sma_l"],1,-1)

In [ ]:
data

In [ ]:
data.loc["2016",["sma_s","sma_l","position"]].plot(figsize=(12,8),title="AAPLE - SMA{} | SMA{}".format(sma_s,sma_l), fontsize=12,secondary_y="position")

In [ ]:
data["returnsb&h"]=np.log(data.Close.div(data.Close.shift(1)))

In [ ]:
data["strategy"]=data["returnsb&h"]*data.position.shift(1)

In [ ]:
data

In [ ]:
data.dropna(inplace=True)

In [ ]:
data[["returnsb&h","strategy"]].sum()

In [ ]:
data[["returnsb&h","strategy"]].sum().apply(np.exp) # what 1$ will be

In [ ]:
data[["returnsb&h","strategy"]].std()*np.sqrt(252) #annyal std

In [ ]:
data.Close.plot(figsize=(12,8))

## Strategy adjusted with long bias

In [ ]:
data["position2"]=np.where(data["sma_s"]>data["sma_l"],1,0)

In [ ]:
data["strategy2"]=data["returnsb&h"]*data.position2.shift(1)

In [ ]:
data.dropna(inplace=True)

In [ ]:
data[["returnsb&h","strategy2"]].sum()

In [ ]:
data[["returnsb&h","strategy2"]].sum().apply(np.exp) # what 1$ will be

In [ ]:
data[["returnsb&h","strategy2"]].std()*np.sqrt(252)

In [ ]:
## Strategy 2 is better than strategy 1
data[["strategy","strategy2"]].std()*np.sqrt(252)

## Find the best SMA for the top 5 stocks
## Create a bias strategy
## Compare drawdowns
## Pick the best 3 stocks for your portfolio

# Creating our first function

In [ ]:
def test_strategy(stock,start,end,SMA):
    df=yf.download(stock,start=start,end=end)
    data=df.Close.to_frame()
    data["returns"]=np.log(data.Close.div(data.Close.shift(1)))
    data["SMA_S"]=data.Close.rolling(int(SMA[0])).mean()
    data["SMA_L"]=data.Close.rolling(int(SMA[1])).mean()
    data.dropna(inplace=True)
    
    data["position"]=np.where(data["SMA_S"]>data["SMA_L"],1,-1)
    data["strategy"]=data["returns"]*data.position.shift(1)
    data.dropna(inplace=True)
    ret=np.exp(data["strategy"].sum())
    std= data["strategy"].std()*np.sqrt(252)
    
    return ret,std

In [ ]:
test_strategy("SPY","2000-01-01","2020-01-01",(50,200))

## Creating our first class

In [35]:
class SMABacktester():
    def __init__(self,symbol,SMA_S, SMA_L,start,end):
        self.symbol=symbol
        self.SMA_S=SMA_S
        self.SMA_L=SMA_L
        self.start=start
        self.end=end
        self.results=None
        self.get_data()
        
    def get_data(self):
        df=yf.download(self.symbol,start=self.start,end=self.end)[['Close']]
        data=df
        data["returns"]=np.log(data.Close.div(data.Close.shift(1)))
        data["SMA_S"]=data.Close.rolling(self.SMA_S).mean()
        data["SMA_L"]=data.Close.rolling(self.SMA_L).mean()
        data.dropna(inplace=True)
        self.data2=data
        
        return data
    
    def test_results(self):
        data=self.data2.copy().dropna()
        data["position"]=np.where(data["SMA_S"]>data["SMA_L"],1,-1)
        data["strategy"]=data["returns"]*data.position.shift(1)
        data.dropna(inplace=True)
        data["returnsbh"]=data["returns"].cumsum().apply(np.exp)
        data["returnsstrategy"]=data["strategy"].cumsum().apply(np.exp)
        perf=data["returnsstrategy"].iloc[-1]
        outperf=perf-data["returnsbh"].iloc[-1]
        self.results=data
        
        ret=np.exp(data["strategy"].sum())
        std= data["strategy"].std()*np.sqrt(252)
    
        #return ret,std
        return round(perf,6), round(outperf,6)
    
    def plot_results(self):
        if self.results is None:
            print("Run the test please")
        else:
            title="{}| SMA_S={} | SMA_L{}".format(self.symbol,self.SMA_S, self.SMA_L)
            self.results[["returnsbh","returnsstrategy"]].plot(title=title, figsize=(12,8))

In [36]:
tester= SMABacktester("SPY",50,100,"2000-01-01","2020-01-01")

/var/folders/4z/0p4c7jt52_d1bq34q6bc_x800000gn/T/ipykernel_79681/125321981.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df=yf.download(self.symbol,start=self.start,end=self.end)[['Close']]
[*********************100%***********************]  1 of 1 completed

In [37]:
tester.test_results()

(3.760714, 0.430827)

In [38]:
tester.plot_results()

## 1. Watch Stan Weinstein Stratgey in our QuantProgram Youtube channel
## 2. Create the stratgey in python
## 3. Backtest it
## 4. Save it as a class in a separate python file.